[platformio]

[env:m5stack-stamps3]
platform = espressif32
board = m5stack-stamps3
framework = arduino
lib_deps =
    m5stack/M5Unified @ ^0.2.14
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=3
    -std=gnu++17

monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_speed = 921600
test_ignore = *
extra_scripts = pre:utils.py  ;injects version into main
build_src_filter =
    +<*.h>
    +<main.cpp>
    -<main_test_native.cpp>

; ---- Native unit tests --------------------------------------
[env:test_native]
platform       = native
build_type     = test
build_flags    =
    -std=gnu++2a
    -D IS_TESTING
test_framework = googletest
lib_deps       =
    googletest
build_src_filter =
    +<main_${PIOENV}.cpp>
test_build_src = yes
