[platformio]

[base_all]
lib_deps =
  lvgl/lvgl @ 9.5.0
  bitbank2/PNGdec @ ^1.0.3 ; instead of stblib, works with less memory
  ArduinoJson @ ~7.4.3
  https://github.com/t413/NavBoxLib#c6656d7
build_src_filter =
  +<*.h>
  +<main_${PIOENV}.cpp>
extra_scripts = pre:utils.py  ;injects version into main

[base_esp32]
extends = base_all
platform = espressif32
board = m5stack-stamps3
framework = arduino
lib_deps =
  ${base_all.lib_deps}
  mikalhart/TinyGPSPlus @ ^1.0.3
build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
  -Werror=return-type
  -Werror=overflow
  -std=gnu++17
  -I include
  -DBOARD_HAS_PSRAM
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_speed = 921600
test_ignore = *
extra_scripts = pre:utils.py  ;injects version into main

[env:m5-s3]
extends = base_esp32
lib_deps =
  ${base_esp32.lib_deps}
  m5stack/M5Unified @ 0.2.13   ; includes partial-lvgl, TJpgDec, Pngle, QRCode, bitwizeshift/result
  m5stack/M5GFX @ 0.2.19       ; only version that works with real lvgl
  m5stack/M5Cardputer @ ^1.1.1
build_flags =
  ${base_esp32.build_flags}
  -D USE_M5
  -D M5GFX_USING_REAL_LVGL=1
  -DBOARD_HAS_PSRAM

[env:tdeck]
extends = base_esp32
board = t-deck
lib_deps =
  ${base_esp32.lib_deps}
  lewisxhe/SensorLib@^0.4.1
  lewisxhe/xPowersLib@^0.3.3
  lovyan03/LovyanGFX
build_flags =
  ${base_esp32.build_flags}
  -D USE_LGFX
  -D BOARD_TDECK_PLUS
  -D BOARD_HAS_PSRAM=1
  -D TILECACHE_SIZE=20


[env:test_native]
extends = base_all
platform = native
build_type = test
build_flags =
  -std=gnu++2a
  -D IS_TESTING
  -I include ;for lv_conf.h
test_framework = googletest
lib_deps =
  googletest
  ${base_all.lib_deps}
  https://github.com/t413/esp32-stb-image ; fork to allow native testing. used for PNG writing
lib_compat_mode = off ;allows PNGdec library
test_build_src = yes
