[platformio]

[base]
lib_deps =
  lvgl/lvgl @ 8.4.0
  bitbank2/PNGdec @ ^1.0.3 ; instead of stblib, works with less memory

[env:m5stack-stamps3]
platform = espressif32
board = m5stack-stamps3
framework = arduino
lib_deps =
  ${base.lib_deps}
  ; lvgl/lvgl @ ^9.3.0 ; needs M5GFX_USING_REAL_LVGL
  m5stack/M5Unified @ 0.2.13   ; includes partial-lvgl, TJpgDec, Pngle, QRCode, bitwizeshift/result
  m5stack/M5GFX @ 0.2.19       ; only version that works with real lvgl
  m5stack/M5Cardputer @ ^1.1.1
  mikalhart/TinyGPSPlus @ ^1.0.3
build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
  ; -DARDUINO_LOOP_STACK_SIZE=16384 ; extra stack addition. default is 8192
  ; -DCORE_DEBUG_LEVEL=3
  -std=gnu++17
  -D M5GFX_USING_REAL_LVGL=1
  -I include
  -DBOARD_HAS_PSRAM
; board_upload.offset_address = 0x210000 ;go into partion2 to avoid launcher

monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_speed = 921600
test_ignore = *
extra_scripts = pre:utils.py  ;injects version into main
build_src_filter =
  +<*.h>
  +<main.cpp>
  -<main_test_native.cpp>

; ---- Native unit tests --------------------------------------
[env:test_native]
platform = native
build_type = test
build_flags =
  -std=gnu++2a
  -D IS_TESTING
  -I include ;for lv_conf.h
test_framework = googletest
lib_deps =
  googletest
  ${base.lib_deps}
  https://github.com/t413/esp32-stb-image ; fork to allow native testing. used for PNG writing
lib_compat_mode = off ;allows PNGdec library
build_src_filter =
  +<main_${PIOENV}.cpp>
test_build_src = yes
